article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path("dashboard/", views.dashboard, name = "dashboard"),
    path("addarticle/", views.addArticle, name = "addarticle"),
    path("article/<int:id>", views.detail, name = "detail"),
    path("update/<int:id>", views.updateArticle, name = "update"),
    path("delete/<int:id>", views.deleteArticle, name = "delete"),
    path("", views.articles, name = "articles"),
    path("comment/<int:id>", views.addComment, name = "comment"),
]

blog_yy/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name = "index"),
    path("about/", views.about, name = "about"),
    path("articles/", include("article.urls")),
    path("user/", include("user.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path("register/", views.register, name = "register"),
    path("login/", views.loginUser, name = "login"),
    path("logout/", views.logoutUser, name = "logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name = "Yazar")
    title = models.CharField(max_length = 50, verbose_name = "Baslik")
    content = RichTextField(verbose_name = "Icerik")
    created_date = models.DateTimeField(auto_now_add = True,verbose_name = "Olusturulma Tarihi")
    article_image = models.FileField(blank = True, null = True, verbose_name = "Makaleye Fotograf Ekleyin")

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ["-created_date"]

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Makale", related_name = "comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "Isim:")
    comment_content = models.CharField(max_length = 200, verbose_name = "Yorum:")
    comment_date = models.DateTimeField(auto_now_add = True)
    
    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ["-comment_date"]

article/forms.py
from django import forms
from django.forms import ModelForm
from .models import Article

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .models import Article, Comment
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# from functools import wraps

# Create your views here.

def user_is_article_author(function):
    def wrap(request, *args, **kwargs):
        article_id = kwargs.get('id')
        article = get_object_or_404(Article, id = article_id)

        if request.user.is_authenticated and request.user == article.author:
            return function(request, *args, **kwargs)
        else:
            messages.info(request, "Bu islem için yetkiniz yok.")
            return redirect("/articles/dashboard")
    return wrap

def index(request):
    return render(request, "index.html")

def about(request):
    return render(request, "about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)

    return render(request, "dashboard.html", {"articles": articles})

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()

        messages.success(request, "Makale Basariyla Eklendi")
        return redirect("article:dashboard")
    else:
        return render(request, "addarticle.html", {"form": form})

def detail(request, id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, id = id)
    comments = article.comments.all()

    return render(request, "detail.html", {"article": article, "comments": comments})

@login_required(login_url = "user:login")
@user_is_article_author
def updateArticle(request, id):
    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance = article)
    
    if form.is_valid():
        article = form.save(commit = False)
        article.author = request.user
        article.save()

        messages.success(request, "Makale Basariyla Guncellendi")
        return redirect("article:dashboard")
    else:
        return render(request, "update.html", {"form": form})

@login_required(login_url = "user:login")
@user_is_article_author
def deleteArticle(request, id):
    article = get_object_or_404(Article, id = id)
    article.delete()

    messages.success(request, "Makale Basariyla Silindi")
    return redirect("article:dashboard")

def articles(request):
    keyword = request.GET.get("keyword")
    
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
    else:
        articles = Article.objects.all()
    
    return render(request, "articles.html", {"articles": articles})

def addComment(request, id):
    article = get_object_or_404(Article, id = id)

    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        
        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()

    return redirect(reverse("article:detail", kwargs = {"id": id}))

templates/about.html
{% extends 'layout.html' %}

{% block body %}
    <h3>Hakkimda</h3>
    <hr>
    <p>Herkese merhaba.Ben Mustafa Murat Coşkun.Odtü Bilgisayar Mühendisliği 4.sınıf öğrencisiyim.Yazılım Bilimi kanalını programlama ve yazılım öğrenmek isteyen gençlere ve yazılımcılara faydalı olmak ,aynı zamanda Türkiyede yazılımın ve eğitimin yükselmesi amacıyla 10 Nisan 2015 tarihinde kurdum.Şimdiye kadar elimden geldiğince video yüklemeye çalıştım.Bu kanaldaki amacım Yazılım Bilimini genel bir online akademiye dönüştürüp Türkiye’nin dört bir yanına ücretsiz bir şekilde eğitim verebilmek.Ülkemizin gençleri olarak hep beraber yazılımı ve bilimi herkese aşılamaya çalışalım.Var mısınız?</p>
    <hr>
{% endblock body %}

templates/addarticle.html
{% extends 'layout.html' %}
{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Makale Olustur</h3>
            <hr>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Makale Ekle</button>
            </form>
        </div>
    </div>
{% endblock body %}

templates/articles.html
{% extends 'layout.html' %}

{% block body %}
    <div class = "row">
        <div class = "col-md-10 offset-md-3">
            <div class="col-lg-8">
                <h3>Makaleler</h3>
                <hr>
            </div>
        </div>
    </div>
    <div class = "row">
        <div class = "col-md-10 offset-md-3">
            <div class="col-lg-8">
                <form>
                    {% csrf_token %}
                    <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ara...">
                    <button type="submit" class="btn btn-danger">Ara</button>
                </form>
            </div>
        </div>
    </div>
    {% if articles %}
        {% for article in articles %}
            <div class="row">
                <div class="col-md-10 offset-md-3">
                    <!-- Post Content Column -->
                    <div class="col-lg-8">

                        <!-- Title-->
                        <a href="{% url 'article:detail' article.id %}"><h2 class="mt-4">{{article.title}}</h2></a>

                        <!-- Author -->
                        <p class="lead">
                            {{article.author.username}} tarafindan yayinlandi
                        </p>
                        <hr>

                        <!-- Date/Time -->
                        <p>{{article.created_date}}</p>
                        <hr>
                        
                        <!-- Preview image figure-->
                        {% if article.article_image %}
                        <a href="{% url 'article:detail' article.id %}"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt=""></a>
                            <hr>
                        {% endif %}
                        
                        <!-- Post content-->
                        <p class = "lead">
                            {{article.content|safe|truncatewords:50}}
                        </p>
                        <a href="{% url 'article:detail' article.id %}" class="btn btn-danger" style="float: right">Devamini Oku</a>
                        <hr>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class = "row">
            <div class = "col-md-10 offset-md-3">
                <div class="col-lg-8">
                    <div class="alert alert-danger">
                        Makale Bulunamadi.
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock body %}

templates/dashboard.html
{% extends 'layout.html' %}
{% block body %}
    <h3>Kontrol Paneli</h3>
    <p>Hosgeldiniz, <small>{{request.user.username}}</small></p>
    <hr>
    <a href="{% url 'article:addarticle' %}" class="btn btn-danger">Makale Ekle</a>
    <hr>
    {% if articles %}
        <table class="table">
            <thead>
              <tr>
                <th scope="col">id</th>
                <th scope="col">Baslik</th>
                <th scope="col">Yazar</th>
                <th scope="col">Tarih</th>
                <th scope="col">Guncelle</th>
                <th scope="col">Sil</th>
              </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr>
                        <th scope="row">{{article.id}}</th>
                        <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
                        <td>{{article.author.username}}</td>
                        <td>{{article.created_date}}</td>
                        <td><a class="btn btn-danger" href="{% url 'article:update' article.id %}">Guncelle</a></td>
                        <td><a class="btn btn-danger" href="{% url 'article:delete' article.id %}">Sil</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-danger">
            Henuz bir makaleniz bulunmuyor...
        </div>
    {% endif %}
{% endblock body %}

templates/detail.html
{% extends 'layout.html' %}
{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <!-- Post Content Column -->
        <div class="col-lg-8">

            <!-- Title-->
            <h3 class="mt-4">{{article.title}}</h3>
            
            <!-- Author -->
            <p class="lead">
                {{article.author.username}} tarafindan yayinlandi
            </p>
            <hr>

            <!-- Date/Time -->
            <p>{{article.created_date}}</p>
            <hr>
            
            <!-- Preview image figure-->
            {% if article.article_image %}
                <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
                <hr>
            {% endif %}
            
            <!-- Post content-->
            <p class = "lead">
                <p>{{article.content|safe}}</p>
            </p>
            <hr>
            <h4>Yorumlar</h4>
            <hr>
            {% if comments %}
                {% for comment in comments %}
                    <div class="media mb-4">
                        <img class="d-flex mr-3 rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..." />
                        <div class="media-body">
                            <h5 class="mt-0">{{comment.comment_author}}</h5>
                            {{comment.comment_date}} <br>
                            {{comment.comment_content}}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-danger">
                    Bu makaleye herhangi bir yorum yazilmamis, ilk yorum yapan siz olun!
                </div>
            {% endif %}

            <div class="card my-4">
                <h5 class = "card-header">Yorum Ekle:</h5>
                <div class="card-body">
                    <form method = "post" action = "{% url 'article:comment' article.id %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="formGroupExampleInput">Isim:</label>
                            <input name="comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="Isminizi girin">
                        </div>
                        <div class="form-group">
                            <label for="formGroupExampleInput">Yorum:</label>
                            <textarea name="comment_content" class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Ekle</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    

{% endblock body %}

templates/index.html
{% extends 'layout.html' %}

{% block body %}
    <div class="jumbotron text-center">
        <h3>Yazilim Bilimi Bloguna Hosgeldiniz</h3>
        <p>Bu blogta gelistiriciler olarak blog yazilarinizi paylasabilirsiniz ve insanlara yardimci olabilirsiniz.</p>
    </div>
    {% if request.user.is_authenticated %}
        <p>Merhaba, {{request.user.username}}</p>
    {% endif %}
{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Yb Blog</title>
</head>
<body>
    {% include 'includes/navbar.html' %}
    
    <div style="margin-top: 100px; margin-bottom: 100px;" class="container">
        {% include 'includes/message.html' %}
        {% block body %}
            
        {% endblock body %}

    </div>




    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/run_prettify.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'layout.html' %}
{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Giris Yap</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button class="btn btn-danger" type="submit">Giris Yap</button>
            </form>
        </div>
    </div>
{% endblock body %}

templates/register.html
{% extends 'layout.html' %}
{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Kayit Olun</h3>
            <hr>
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button class="btn btn-danger" type="submit">Kayit Ol</button>
            </form>
        </div>
    </div>
{% endblock body %}

templates/update.html
{% extends 'layout.html' %}
{% block body %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Makale Guncelle</h3>
            <hr>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Makale Guncelle</button>
            </form>
        </div>
    </div>
{% endblock body %}